//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabiticaTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultTaskItem
    {
        public int TaskItemsId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> TaskId { get; set; }
    
        public virtual DefaultTask DefaultTask { get; set; }
    }
}
