//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabiticaTravel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class habiticatravelEntities : DbContext
    {
        public habiticatravelEntities()
            : base("name=habiticatravelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HabiticaUser> HabiticaUsers { get; set; }
        public virtual DbSet<UserStat> UserStats { get; set; }
        public virtual DbSet<CustomTaskItem> CustomTaskItems { get; set; }
        public virtual DbSet<DefaultTaskItem> DefaultTaskItems { get; set; }
        public virtual DbSet<TravelGroup> TravelGroups { get; set; }
        public virtual DbSet<TravelGroupUser> TravelGroupUsers { get; set; }
        public virtual DbSet<DefaultTask> DefaultTasks { get; set; }
        public virtual DbSet<CustomTask> CustomTasks { get; set; }
    }
}
