//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabiticaTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HabiticaUser
    {
        public int HabiticaUserId { get; set; }
        public string Uuid { get; set; }
        public string ApiToken { get; set; }
        public string UserId { get; set; }
    }
}
