//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabiticaTravel.Models
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TravelGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravelGroup()
        {
            this.TravelGroupUsers = new HashSet<TravelGroupUser>();
            this.CustomTasks = new HashSet<CustomTask>();
        }
    
        public int TravelGroupId { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = " Name must be between 1 and 20 characters long.")]
        [RegularExpression("^[a-zA-Z0-9_-]*$")]
        [Display(Name = "Group Name")]
        public string TravelGroupName { get; set; }

        [Required]
        [RegularExpression(@"^\d{5}$")]
        [Display(Name = "Destination")]
        public string Destination { get; set; }

        [Required]
        [Display(Name = "Transportaion Type")]
        public string TravelMethod { get; set; }
        public string GroupLeader { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelGroupUser> TravelGroupUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomTask> CustomTasks { get; set; }
    }
}
