//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabiticaTravel.Models
{
    using System;

    public partial class UserStat
    {
        public int ProfileId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> UserStatsPer { get; set; }
        public Nullable<int> UserStats_int { get; set; }
        public Nullable<int> UserStatsCon { get; set; }
        public Nullable<int> UserStatsStr { get; set; }
        public Nullable<int> UserStatsPoints { get; set; }
        public string UserStats_class { get; set; }
        public Nullable<int> UserStatsLvl { get; set; }
        public Nullable<int> UserStatsGp { get; set; }
        public Nullable<int> UserStatsExp { get; set; }
        public Nullable<int> UserStatsMp { get; set; }
        public Nullable<int> UserStatsHp { get; set; }
        public Nullable<int> UserStatsToNextLevel { get; set; }
        public Nullable<int> UserStatsMaxHealth { get; set; }
        public Nullable<int> UserStatsMaxMP { get; set; }
        public Nullable<int> TrainingCon { get; set; }
        public Nullable<int> TrainingStr { get; set; }
        public Nullable<int> TrainingPer { get; set; }
        public Nullable<int> Training_int { get; set; }
        public Nullable<bool> BuffsSeafoam { get; set; }
        public Nullable<bool> BuffsShinySeed { get; set; }
        public Nullable<bool> BuffsSpookySparkles { get; set; }
        public Nullable<bool> BuffsSnowball { get; set; }
        public Nullable<bool> BuffsStreaks { get; set; }
        public Nullable<int> BuffsStealth { get; set; }
        public Nullable<int> BuffsCon { get; set; }
        public Nullable<int> BuffsPer { get; set; }
        public Nullable<int> Buffs_int { get; set; }
        public Nullable<int> BuffsStr { get; set; }
        public string ProfileName { get; set; }
        public string ProfilePhoto { get; set; }
        public string ProfileBlurb { get; set; }
    }
}
